### ISSUE TITLE
Add more optional features to the main futures crate

### ISSUE THREAD

**Issue by seanmonstar** [rust-lang/futures-rs#1875] opened 2019-09-17 17:15 UTC
For convenience, the `futures` (well, `futures-preview` for now) crate re-exports from *all* of the futures-*. This can be a nice first experience, being able to use streams, sinks, channels, and what-not out-of-the-box. However, due to this, other libraries have been removing their dependency on `futures` to a smaller group that they need (such as `futures-core` and `futures-util`).

I think it could be useful if a library could depend on `futures` while disabling the pieces they don't need. So, like in hyper, it could have `futures = { version = "0.3", default-features = false, features = ["util"] }`.

**Comment by Pauan** [comment] 2019-09-17 18:18
Unfortunately, that doesn't work. Imagine you have this crate layout:

```
    futures
 /          \
A            B
 \          /
      C
```

Let's suppose that crate A uses `default-features = false`, but crate B does not.

In that case all of the default features will be enabled, and there is nothing crates A or C can do about it.

Some more context [here](https://github.com/rust-lang-nursery/futures-rs/issues/1489#issuecomment-475896439).

**Comment by Nemo157** [comment] 2019-09-17 18:27
That’s absolutely fine, if `A` only needs some limited subset of features but `B` needs them all then that is features working as intended. If `B` doesn’t need them all then that indicates that there needs to be more understanding in the ecosystem that `default-features = false` should be the default stance you take to all dependencies, and just activate what features you need.

**Comment by Pauan** [comment] 2019-09-17 19:06
> @Nemo157 If B doesn’t need them all then that indicates that there needs to be more understanding in the ecosystem that default-features = false should be the default stance you take to all dependencies, and just activate what features you need.

Yes, that's exactly the problem. *Every* crate would need to use `default-features = false` and only enable the features they want. Even a single crate messing it up will affect every other crate.

Unfortunately, it's far too easy to mess up `default-features` and forget to use it. That problem doesn't happen nearly as much with separate crates (where there is a clear implicit understanding that an umbrella crate pulls in everything).

So, as an alternative suggestion, what if *nothing* was enabled by default in `futures`, and you had to selectively enable individual features. Then there would be an `all` feature which enables all the other features:

```toml
[dependencies]
util = { version = "0.3.0", optional = true, package = "futures-util" }
core = { version = "0.3.0", optional = true, package = "futures-core" }
executor = { version = "0.3.0", optional = true, package = "futures-executor" }

[features]
all = ["core", "util", "executor"]
```

This means you don't need to use `default-features = false` (which avoids all the issues with it), and it makes it impossible to screw up: you cannot accidentally enable all features.

**Comment by taiki-e** [comment] 2020-06-05 23:34
> features = ["util"]

FYI: It is impossible to add the "util" feature with the current crate-layout (because the `std` and `alloc` features cannot be properly propagated).
To separate "util" by a feature flag, it needs to merge `futures` and `futures-util`, and implement [auto-detection based no-std support](https://github.com/bluss/indexmap/blob/da1835123cc489eeaa7a83da961c0031e17adc79/build.rs#L5) for most sub crates (or merge most sub crates).

**Comment by taiki-e** [comment] 2023-07-20 16:24
Closing in favor of https://github.com/rust-lang/futures-rs/issues/2295.

**Closed by taiki-e** 2023-07-20 16:24 UTC
Labels: S-needs-api-design, S-needs-decision
