### ISSUE TITLE
Move to parking_lot::Mutex for mutex and away from std::sync::Mutex?

### ISSUE THREAD

**Issue by bluejekyll** [rust-lang/futures-rs#2496] opened 2021-09-14 17:29 UTC
`parking_lot` has a lot of advantages over `std::sync::Mutex`.

Should we migrate to `parking_lot` for all `futures_util::lock` primitives?

If we're open to this, I'd be happy to contribute the work for this.

**Comment by taiki-e** [comment] 2021-09-15 08:10
I would accept a PR to add an *optional* feature to do this.
(parking_lot is very good, but note that it may fail to compile on some platforms. futures needs to work on such platforms. e.g., https://github.com/Amanieu/parking_lot/issues/269)

**Comment by lilyball** [comment] 2021-10-30 18:10
I would love to see a `parking_lot` feature. I keep ending up taking code using `parking_lot::Mutex` and changing it to `futures::lock::Mutex` because it's being used in an async context, and this feels like a regression.

**Comment by ibraheemdev** [comment] 2022-06-05 03:54
Given the work going on to improve `std::sync::Mutex`, it might not be of much benefit to add this now.

**Comment by taiki-e** [comment] 2022-06-05 04:00
I agreed with @ibraheemdev, and tend to close this for now.

relevant discussion: https://github.com/tokio-rs/tokio/issues/4623

**Closed by taiki-e** 2022-06-05 04:00 UTC
Labels: C-feature-request, A-lock
