### ISSUE TITLE
buffered(0) streams hang forever

### ISSUE THREAD

**Issue by kuecks** [rust-lang/futures-rs#2876] opened 2024-08-03 00:42 UTC
If you somehow pass in 0 as the concurrency limit to the buffered methods (buffered_unordered, try_buffered_unordered etc.) then the underlying stream will never be polled and as a result, the stream will never be "done" (https://docs.rs/futures-util/0.3.30/src/futures_util/stream/try_stream/try_buffer_unordered.rs.html#68-72). Therefore, the stream will always return `Pending` and any code trying to consume the stream will just hang. I can't imagine someone wanting this behavior (and it impacted one of my teammates and took a long time to debug), so I feel like the code should either silently treat a buffer size of 0 as 1, or panic (or take in a NonZeroUsize, but that seems overkill)

playground repro: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c941ce1e13e1081aaf33f3c580c53898

**Comment by taiki-e** [comment] 2024-08-03 03:46
Duplicate of #2348

**Closed by taiki-e** 2024-08-03 03:46 UTC
