### ISSUE TITLE
`try_collect` into `Option<Vec<T>>`

### ISSUE THREAD

**Issue by tqwewe** [rust-lang/futures-rs#2653] opened 2022-10-16 14:44 UTC
Given a stream of `Result<Option<T>>`, I'd like to `.try_collect` into an `Option<Vec<T>>`, but it seems like this is not supported.

Is there any obvious reason for this?

Currently my workaround is:
```rust
let workers = ...; // some stream of Result<Option<T>>

let items = workers
  .try_collect::<Vec<_>>()
  .await?
  .into_iter()
  .collect::<Option<Vec<_>>>();
```
Or a manual while loop pushing to a vec.

**Comment by taiki-e** [comment] 2022-10-16 14:56
Duplicate of #1833.

**Closed by taiki-e** 2022-10-16 14:56 UTC
