### ISSUE TITLE
Broken intra-rustdoc-links

### ISSUE THREAD

**Issue by olegnn** [rust-lang/futures-rs#1903] opened 2019-10-08 07:39 UTC
I created an issue https://github.com/rust-lang/rust/issues/64193 month ago and there's no progress at all up to 8 october. The problem is that [intra-rustdoc-links](https://rust-lang.github.io/rfcs/1946-intra-rustdoc-links.html) don't work correctly.

Now these links (for ex.)

- https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.19/futures/channel/mpsc/struct.TrySendError.html => `try_send`, 
- https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.19/futures/channel/mpsc/struct.Sender.html => `channel`

don't redirect to correct destination, moreover in some places without context reader can't understand method of which `trait`/`impl`/`mod` is mentioned. 

If change them to the full path, we will get warnings (see issue), however links will work. Maybe it's ok for now to have warnings but correctly working links? I could prepare PR with expanded links.

**Comment by Nemo157** [comment] 2019-10-08 08:36
This seems to be somewhat related to https://github.com/rust-lang/rust/issues/60883, the link from [`futures_channel::mpsc::TrySendError`](https://docs.rs/futures-channel-preview/0.3.0-alpha.19/futures_channel/mpsc/struct.TrySendError.html) works, but the link from [`futures::channel::mpsc::TrySendError`](https://docs.rs/futures-preview/0.3.0-alpha.19/futures/channel/mpsc/struct.TrySendError.html) doesn't.

Applying the suggested change to use an absolute path (`mpsc::Sender::try_send`) inverts that, the link in the `futures` docs will start working while the link in `futures-channel` will stop working (which is why there is a warning emitted). I really don't understand why this is, the absolute path is only valid in `futures-channel`, so how come it works in the opposite case?

**Comment by olegnn** [comment] 2019-10-08 09:06
I didn't pay attention that link from `futures_channel::channel::mpsc::TrySendError` won't work after changing to absolute path, so then we have 1 correct warning at least. 

This's especially strange because after change to `futures_channel::mpsc::Receiver::try_next()` link from `futures::...` will work normally, however link from `futures_channel::...` won't resolve but will generate incorrect url (which is a link with prefix and unresolved path).

**Comment by jyn514** [comment] 2020-07-20 14:31
I think this should be fixed now that https://github.com/rust-lang/rust/issues/65983 has been fixed :)

**Comment by taiki-e** [comment] 2020-09-05 11:20
Confirmed this has been fixed 🎉

**Closed by taiki-e** 2020-09-05 11:21 UTC
Labels: docs
